package ui

import (
	"encoding/base64"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/blank-query/lazyVPN-for-Omarchy/internal/config"
	"github.com/blank-query/lazyVPN-for-Omarchy/internal/provider"
	"github.com/blank-query/lazyVPN-for-Omarchy/internal/wireguard"
	tea "github.com/charmbracelet/bubbletea"
)

func TestDetectProviderByDNS(t *testing.T) {
	tests := []struct {
		name string
		dns  string
		want string
	}{
		{"protonvpn", "10.2.0.1", "protonvpn"},
		{"protonvpn comma", "10.2.0.1, fd00::1", "protonvpn"},
		{"mullvad primary", "10.64.0.1", "mullvad"},
		{"mullvad secondary", "193.138.218.74", "mullvad"},
		{"ivpn", "172.16.0.1", "ivpn"},
		{"airvpn", "10.128.0.1", "airvpn"},
		{"nordvpn", "103.86.96.100", "nordvpn"},
		{"surfshark", "162.252.172.57", "surfshark"},
		{"windscribe", "10.255.255.1", "windscribe"},
		{"fastestvpn", "10.8.0.1", "fastestvpn"},
		{"unknown dns", "8.8.8.8", ""},
		{"empty dns", "", ""},
		{"comma prefix mullvad", "fd00::1,10.64.0.1", "mullvad"},
		{"space prefix mullvad", "fd00::1 10.64.0.1", "mullvad"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := &wireguard.Config{DNS: tt.dns}
			got := detectProvider("", cfg)
			if got != tt.want {
				t.Errorf("detectProvider(dns=%q) = %q, want %q", tt.dns, got, tt.want)
			}
		})
	}
}

func TestDetectProviderByEndpoint(t *testing.T) {
	tests := []struct {
		name     string
		endpoint string
		want     string
	}{
		{"protonvpn endpoint", "node-us-01.protonvpn.net:51820", "protonvpn"},
		{"mullvad endpoint", "se-got-wg-001.mullvad.net:51820", "mullvad"},
		{"ivpn endpoint", "us1.gw.ivpn.net:2049", "ivpn"},
		{"airvpn endpoint", "alderamin.airvpn.org:1637", "airvpn"},
		{"nordvpn endpoint", "us1234.nordvpn.com:51820", "nordvpn"},
		{"surfshark endpoint", "us-dal.prod.surfshark.com:51820", "surfshark"},
		{"windscribe endpoint", "yyz-01.windscribe.com:443", "windscribe"},
		{"fastestvpn endpoint", "au-01.jumptoserver.com:51820", "fastestvpn"},
		{"unknown endpoint", "198.51.100.1:51820", ""},
		{"airvpn port hint only", "198.51.100.1:1637", "airvpn"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := &wireguard.Config{Endpoint: tt.endpoint}
			got := detectProvider("", cfg)
			if got != tt.want {
				t.Errorf("detectProvider(endpoint=%q) = %q, want %q", tt.endpoint, got, tt.want)
			}
		})
	}
}

func TestDetectProviderByFileContent(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{"protonvpn comment", "# ProtonVPN WireGuard config\n[Interface]\n", "protonvpn"},
		{"mullvad comment", "# Mullvad server config\n[Interface]\n", "mullvad"},
		{"ivpn content", "# Generated by IVPN\n[Interface]\n", "ivpn"},
		{"airvpn content", "# AirVPN WireGuard config\n[Interface]\n", "airvpn"},
		{"nordvpn content", "# NordVPN server\n[Interface]\n", "nordvpn"},
		{"nordlynx content", "# NordLynx\n[Interface]\n", "nordvpn"},
		{"surfshark content", "# Surfshark WireGuard\n[Interface]\n", "surfshark"},
		{"windscribe content", "# Windscribe config\n[Interface]\n", "windscribe"},
		{"fastestvpn content", "# FastestVPN config\n[Interface]\n", "fastestvpn"},
		{"no match", "# Generic VPN config\n[Interface]\n", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			path := filepath.Join(tmpDir, "test.conf")
			os.WriteFile(path, []byte(tt.content), 0600)

			cfg := &wireguard.Config{} // empty DNS and Endpoint
			got := detectProvider(path, cfg)
			if got != tt.want {
				t.Errorf("detectProvider(content=%q) = %q, want %q", tt.content, got, tt.want)
			}
		})
	}
}

func TestDetectProviderByAddressRange(t *testing.T) {
	tests := []struct {
		name    string
		address string
		want    string
	}{
		{"protonvpn address", "10.2.0.2/32", "protonvpn"},
		{"mullvad 64", "10.64.222.53/32", "mullvad"},
		{"mullvad 65", "10.65.1.1/32", "mullvad"},
		{"ivpn address", "172.16.0.2/32", "ivpn"},
		{"airvpn address", "10.128.0.2/32", "airvpn"},
		{"windscribe address", "10.255.255.2/32", "windscribe"},
		{"fastestvpn address", "10.8.0.2/32", "fastestvpn"},
		{"ambiguous 192.168", "192.168.1.2/32", ""},
		{"ambiguous 10.0", "10.0.0.2/32", ""},
		{"empty address", "", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Empty DNS/endpoint/content — force fallthrough to address check.
			cfg := &wireguard.Config{Address: tt.address}
			got := detectProvider("", cfg)
			if got != tt.want {
				t.Errorf("detectProvider(address=%q) = %q, want %q", tt.address, got, tt.want)
			}
		})
	}
}

func TestDetectProviderDNSTakesPriority(t *testing.T) {
	// DNS detection should match before endpoint detection
	cfg := &wireguard.Config{
		DNS:      "10.2.0.1",
		Endpoint: "se-got-wg-001.mullvad.net:51820",
	}
	got := detectProvider("", cfg)
	if got != "protonvpn" {
		t.Errorf("DNS should take priority over endpoint: got %q, want protonvpn", got)
	}
}

func TestDetectProviderCaseInsensitive(t *testing.T) {
	// DNS is lowercased, so mixed case should work
	cfg := &wireguard.Config{DNS: "10.2.0.1"}
	got := detectProvider("", cfg)
	if got != "protonvpn" {
		t.Errorf("got %q, want protonvpn", got)
	}

	// Endpoint with mixed case
	cfg2 := &wireguard.Config{Endpoint: "node-US-01.PROTONVPN.NET:51820"}
	got2 := detectProvider("", cfg2)
	if got2 != "protonvpn" {
		t.Errorf("mixed-case endpoint: got %q, want protonvpn", got2)
	}
}

// newTestProviderSetup creates a ProviderSetup with predefined files for testing.
func newTestProviderSetup(t *testing.T) *ProviderSetup {
	t.Helper()
	cfg := config.DefaultConfig()
	cfg.ConfigDir = t.TempDir()
	cfg.ConfigFile = filepath.Join(cfg.ConfigDir, "config.json")
	os.MkdirAll(cfg.ConfigDir, 0700)

	return &ProviderSetup{
		cfg:  cfg,
		step: StepSelectFile,
		files: []configFile{
			{path: "/tmp/valid.conf", name: "valid.conf", provider: "protonvpn", valid: true, privateKey: []byte("AAAA1234567890AAAA1234567890AAAA12"), address: "10.2.0.2/32"},
			{path: "/tmp/invalid.conf", name: "invalid.conf", valid: false},
		},
	}
}

func TestProviderSetupInit(t *testing.T) {
	ps := newTestProviderSetup(t)
	if ps.Init() != nil {
		t.Error("Init should return nil")
	}
}

func TestProviderSetupStepConstants(t *testing.T) {
	if StepSelectFile != 0 {
		t.Errorf("StepSelectFile = %d, want 0", StepSelectFile)
	}
	if StepComplete != 4 {
		t.Errorf("StepComplete = %d, want 4", StepComplete)
	}
	if StepError != 5 {
		t.Errorf("StepError = %d, want 5", StepError)
	}
}

func TestProviderSetupFileSelectEsc(t *testing.T) {
	ps := newTestProviderSetup(t)
	_, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyEscape})
	if cmd == nil {
		t.Fatal("esc should return cmd")
	}
	msg := cmd()
	if _, ok := msg.(BackMsg); !ok {
		t.Errorf("expected BackMsg, got %T", msg)
	}
}

func TestProviderSetupFileSelectCursor(t *testing.T) {
	ps := newTestProviderSetup(t)

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyDown})
	ps = model.(*ProviderSetup)
	if ps.cursor != 1 {
		t.Errorf("cursor = %d, want 1", ps.cursor)
	}

	model, _ = ps.Update(tea.KeyMsg{Type: tea.KeyDown})
	ps = model.(*ProviderSetup)
	if ps.cursor != 1 {
		t.Errorf("cursor = %d, want 1 (clamped)", ps.cursor)
	}

	model, _ = ps.Update(tea.KeyMsg{Type: tea.KeyUp})
	ps = model.(*ProviderSetup)
	if ps.cursor != 0 {
		t.Errorf("cursor = %d, want 0", ps.cursor)
	}

	model, _ = ps.Update(tea.KeyMsg{Type: tea.KeyUp})
	ps = model.(*ProviderSetup)
	if ps.cursor != 0 {
		t.Errorf("cursor = %d, want 0 (clamped)", ps.cursor)
	}
}

func TestProviderSetupFileSelectInvalidFile(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.cursor = 1 // invalid file

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	ps = model.(*ProviderSetup)

	if ps.step != StepSelectFile {
		t.Errorf("step = %d, should stay on StepSelectFile for invalid file", ps.step)
	}
	if ps.message == "" {
		t.Error("should set error message for invalid file")
	}
}

func TestProviderSetupFileSelectValidWithProvider(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.cursor = 0 // valid file with detected provider

	model, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	ps = model.(*ProviderSetup)

	// Provider was detected, so it should try to save (step = StepSaving)
	// or go to overwrite confirmation if already configured
	if ps.step != StepSaving {
		t.Errorf("step = %d, want StepSaving", ps.step)
	}
	if ps.confirmedProv != "protonvpn" {
		t.Errorf("confirmedProv = %q, want protonvpn", ps.confirmedProv)
	}
	if cmd == nil {
		t.Error("should return save command")
	}
}

func TestProviderSetupFileSelectValidNoProvider(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.files[0].provider = "" // clear provider
	ps.cursor = 0

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	ps = model.(*ProviderSetup)

	if ps.step != StepConfirmProvider {
		t.Errorf("step = %d, want StepConfirmProvider", ps.step)
	}
}

func TestProviderSetupFileSelectAlreadyConfigured(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.cursor = 0

	// Create existing provider file
	provDir := filepath.Join(ps.cfg.ConfigDir, "providers")
	os.MkdirAll(provDir, 0700)
	os.WriteFile(filepath.Join(provDir, "protonvpn.json"), []byte(`{"private_key":"test","address":"10.2.0.2/32"}`), 0600)

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	ps = model.(*ProviderSetup)

	if ps.step != StepConfirmOverwrite {
		t.Errorf("step = %d, want StepConfirmOverwrite", ps.step)
	}
	if !ps.alreadyConfigured {
		t.Error("alreadyConfigured should be true")
	}
}

func TestProviderSetupConfirmProviderEsc(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyEscape})
	ps = model.(*ProviderSetup)

	if ps.step != StepSelectFile {
		t.Errorf("step = %d, want StepSelectFile (back)", ps.step)
	}
}

func TestProviderSetupConfirmProviderCycle(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = "protonvpn"

	// Down should cycle to next provider
	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyDown})
	ps = model.(*ProviderSetup)
	if ps.confirmedProv != "mullvad" {
		t.Errorf("confirmedProv = %q, want mullvad", ps.confirmedProv)
	}

	// Up should cycle back
	model, _ = ps.Update(tea.KeyMsg{Type: tea.KeyUp})
	ps = model.(*ProviderSetup)
	if ps.confirmedProv != "protonvpn" {
		t.Errorf("confirmedProv = %q, want protonvpn", ps.confirmedProv)
	}
}

func TestProviderSetupConfirmProviderCycleWrapDown(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = "fastestvpn" // last provider

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyDown})
	ps = model.(*ProviderSetup)
	if ps.confirmedProv != "protonvpn" {
		t.Errorf("confirmedProv = %q, want protonvpn (wrapped)", ps.confirmedProv)
	}
}

func TestProviderSetupConfirmProviderCycleWrapUp(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = "protonvpn" // first provider

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyUp})
	ps = model.(*ProviderSetup)
	if ps.confirmedProv != "fastestvpn" {
		t.Errorf("confirmedProv = %q, want fastestvpn (wrapped)", ps.confirmedProv)
	}
}

func TestProviderSetupConfirmProviderEmptyDefault(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = "" // empty

	// Down should set to first provider
	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyDown})
	ps = model.(*ProviderSetup)
	if ps.confirmedProv != "protonvpn" {
		t.Errorf("confirmedProv = %q, want protonvpn", ps.confirmedProv)
	}
}

func TestProviderSetupConfirmProviderEnterEmpty(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = ""

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	ps = model.(*ProviderSetup)

	if ps.step != StepConfirmProvider {
		t.Errorf("step = %d, should stay on StepConfirmProvider", ps.step)
	}
	if ps.message == "" {
		t.Error("should set please select message")
	}
}

func TestProviderSetupConfirmProviderEnter(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = "mullvad"

	model, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	ps = model.(*ProviderSetup)

	if ps.step != StepSaving {
		t.Errorf("step = %d, want StepSaving", ps.step)
	}
	if cmd == nil {
		t.Error("should return save command")
	}
}

func TestProviderSetupConfirmProviderEnterAlreadyConfigured(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = "mullvad"

	// Create existing provider file
	provDir := filepath.Join(ps.cfg.ConfigDir, "providers")
	os.MkdirAll(provDir, 0700)
	os.WriteFile(filepath.Join(provDir, "mullvad.json"), []byte(`{"private_key":"test","address":"10.2.0.2/32"}`), 0600)

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	ps = model.(*ProviderSetup)

	if ps.step != StepConfirmOverwrite {
		t.Errorf("step = %d, want StepConfirmOverwrite", ps.step)
	}
}

func TestProviderSetupOverwriteConfirmYes(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmOverwrite
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = "protonvpn"

	model, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'y'}})
	ps = model.(*ProviderSetup)

	if ps.step != StepSaving {
		t.Errorf("step = %d, want StepSaving", ps.step)
	}
	if cmd == nil {
		t.Error("should return save command")
	}
}

func TestProviderSetupOverwriteConfirmNo(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmOverwrite
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = "protonvpn"
	ps.alreadyConfigured = true

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'n'}})
	ps = model.(*ProviderSetup)

	if ps.step != StepSelectFile {
		t.Errorf("step = %d, want StepSelectFile (cancel)", ps.step)
	}
	if ps.alreadyConfigured {
		t.Error("alreadyConfigured should be reset")
	}
}

func TestProviderSetupOverwriteConfirmEsc(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmOverwrite
	ps.selectedFile = &ps.files[0]

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyEscape})
	ps = model.(*ProviderSetup)

	if ps.step != StepSelectFile {
		t.Errorf("step = %d, want StepSelectFile (cancel)", ps.step)
	}
}

func TestProviderSetupCompleteEnter(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete
	ps.fetchServers = true

	_, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	if cmd == nil {
		t.Fatal("enter on complete should return cmd")
	}
	msg := cmd()
	if _, ok := msg.(BackMsg); !ok {
		t.Errorf("expected BackMsg, got %T", msg)
	}
}

func TestProviderSetupCompleteBlockedBeforeFetch(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete
	ps.fetchServers = false

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	ps = model.(*ProviderSetup)

	// Should stay on StepComplete (blocked until fetch is done)
	if ps.step != StepComplete {
		t.Errorf("step = %d, should stay on StepComplete", ps.step)
	}
}

func TestProviderSetupCompleteEsc(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete
	ps.fetchServers = true

	_, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyEscape})
	if cmd == nil {
		t.Fatal("esc on complete should return cmd")
	}
	msg := cmd()
	if _, ok := msg.(BackMsg); !ok {
		t.Errorf("expected BackMsg, got %T", msg)
	}
}

func TestProviderSetupErrorEnter(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepError
	ps.errorMsg = "test error"

	_, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	if cmd == nil {
		t.Fatal("enter on error should return cmd")
	}
	msg := cmd()
	if _, ok := msg.(BackMsg); !ok {
		t.Errorf("expected BackMsg, got %T", msg)
	}
}

func TestProviderSetupErrorEsc(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepError

	_, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyEscape})
	if cmd == nil {
		t.Fatal("esc on error should return cmd")
	}
	msg := cmd()
	if _, ok := msg.(BackMsg); !ok {
		t.Errorf("expected BackMsg, got %T", msg)
	}
}

func TestProviderSetupWindowSize(t *testing.T) {
	ps := newTestProviderSetup(t)

	model, _ := ps.Update(tea.WindowSizeMsg{Width: 100, Height: 30})
	ps = model.(*ProviderSetup)

	if ps.width != 100 || ps.height != 30 {
		t.Errorf("size = %dx%d, want 100x30", ps.width, ps.height)
	}
}

func TestProviderSetupSuccessMsg(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepSaving

	model, cmd := ps.Update(providerSetupSuccessMsg{})
	ps = model.(*ProviderSetup)

	if ps.step != StepComplete {
		t.Errorf("step = %d, want StepComplete", ps.step)
	}
	if cmd == nil {
		t.Error("should return fetch command")
	}
}

func TestProviderSetupErrorMsg(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepSaving

	model, _ := ps.Update(providerSetupErrorMsg{err: errors.New("save failed")})
	ps = model.(*ProviderSetup)

	if ps.step != StepError {
		t.Errorf("step = %d, want StepError", ps.step)
	}
	if ps.errorMsg != "save failed" {
		t.Errorf("errorMsg = %q, want 'save failed'", ps.errorMsg)
	}
}

func TestProviderSetupFetchDoneMsg(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete

	model, _ := ps.Update(providerFetchDoneMsg{})
	ps = model.(*ProviderSetup)

	if !ps.fetchServers {
		t.Error("fetchServers should be true")
	}
	if ps.message != "Server list fetched!" {
		t.Errorf("message = %q, want 'Server list fetched!'", ps.message)
	}
}

func TestProviderSetupViewSelectFile(t *testing.T) {
	ps := newTestProviderSetup(t)

	view := ps.View()
	if !strings.Contains(view, "Provider Setup") {
		t.Error("should contain Provider Setup title")
	}
	if !strings.Contains(view, "valid.conf") {
		t.Error("should show valid.conf")
	}
	if !strings.Contains(view, "invalid.conf") {
		t.Error("should show invalid.conf")
	}
	if !strings.Contains(view, "VALID") {
		t.Error("should show VALID status")
	}
	if !strings.Contains(view, "INVALID") {
		t.Error("should show INVALID status")
	}
}

func TestProviderSetupViewSelectFileEmpty(t *testing.T) {
	cfg := config.DefaultConfig()
	cfg.ConfigDir = t.TempDir()
	ps := &ProviderSetup{cfg: cfg, step: StepSelectFile}

	view := ps.View()
	if !strings.Contains(view, "No .conf files") {
		t.Error("should show no files message")
	}
}

func TestProviderSetupViewSelectFileWithMessage(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.message = "Test error message"

	view := ps.View()
	if !strings.Contains(view, "Test error message") {
		t.Error("should show error message")
	}
}

func TestProviderSetupViewConfirmProvider(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.detectedProv = "protonvpn"
	ps.confirmedProv = "protonvpn"

	view := ps.View()
	if !strings.Contains(view, "Confirm Provider") {
		t.Error("should contain Confirm Provider title")
	}
	if !strings.Contains(view, "valid.conf") {
		t.Error("should show selected file name")
	}
	if !strings.Contains(view, "Detected") {
		t.Error("should show detected provider")
	}
}

func TestProviderSetupViewConfirmProviderNoDetection(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.detectedProv = ""

	view := ps.View()
	if !strings.Contains(view, "Could not auto-detect") {
		t.Error("should show auto-detect failure message")
	}
}

func TestProviderSetupViewConfirmOverwrite(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmOverwrite
	ps.selectedFile = &ps.files[0]
	ps.confirmedProv = "protonvpn"

	view := ps.View()
	if !strings.Contains(view, "Already Configured") {
		t.Error("should contain Already Configured title")
	}
	if !strings.Contains(view, "WARNING") {
		t.Error("should show warning")
	}
	if !strings.Contains(view, "Overwrite") {
		t.Error("should ask about overwrite")
	}
}

func TestProviderSetupViewSaving(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepSaving

	view := ps.View()
	if !strings.Contains(view, "Saving") {
		t.Error("should contain Saving title")
	}
}

func TestProviderSetupViewComplete(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete
	ps.confirmedProv = "protonvpn"
	ps.fetchServers = false

	view := ps.View()
	if !strings.Contains(view, "Setup Complete") {
		t.Error("should contain Setup Complete title")
	}
	if !strings.Contains(view, "Fetching server list") {
		t.Error("should show fetching message when not done")
	}
}

func TestProviderSetupViewCompleteWithFetch(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete
	ps.confirmedProv = "protonvpn"
	ps.fetchServers = true
	ps.selectedFile = &ps.files[0]

	view := ps.View()
	if !strings.Contains(view, "Server list fetched") {
		t.Error("should show fetched message")
	}
	if !strings.Contains(view, "Delete it?") {
		t.Error("should ask about deleting source file")
	}
}

func TestProviderSetupViewError(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepError
	ps.errorMsg = "something went wrong"

	view := ps.View()
	if !strings.Contains(view, "Error") {
		t.Error("should contain Error title")
	}
	if !strings.Contains(view, "something went wrong") {
		t.Error("should show error message")
	}
}

func TestProviderSetupViewKeyDisplay(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmProvider
	ps.selectedFile = &ps.files[0]
	ps.selectedFile.privateKey = []byte("ABCDEFGH1234567890abcdefgh12345678")

	view := ps.View()
	// Key should be truncated in the view (displayed as base64)
	fullB64 := base64.StdEncoding.EncodeToString(ps.selectedFile.privateKey)
	if strings.Contains(view, fullB64) {
		t.Error("should not show full private key")
	}
}

func TestProviderSetupFileSelectEmptyFiles(t *testing.T) {
	cfg := config.DefaultConfig()
	cfg.ConfigDir = t.TempDir()
	ps := &ProviderSetup{cfg: cfg, step: StepSelectFile, files: nil}

	// Enter with no files should be a no-op
	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyEnter})
	ps = model.(*ProviderSetup)
	if ps.step != StepSelectFile {
		t.Errorf("step should remain StepSelectFile")
	}
}

func TestProviderSetupCompleteYesKey(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete
	ps.fetchServers = true
	ps.selectedFile = &configFile{
		path: "/tmp/nonexistent-provsetup-test.conf",
	}

	_, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'y'}})
	if cmd == nil {
		t.Fatal("y on complete should return cmd")
	}
	msg := cmd()
	if _, ok := msg.(BackMsg); !ok {
		t.Errorf("expected BackMsg, got %T", msg)
	}
}

func TestProviderSetupCompleteYesKeyAlreadyDeleted(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete
	ps.fetchServers = true
	ps.selectedFile = &configFile{
		path: "/tmp/nonexistent.conf",
	}
	_, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'Y'}})
	if cmd == nil {
		t.Fatal("Y on complete should return cmd")
	}
	msg := cmd()
	if _, ok := msg.(BackMsg); !ok {
		t.Errorf("expected BackMsg, got %T", msg)
	}
}

func TestProviderSetupCompleteYesKeyNoSelectedFile(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete
	ps.fetchServers = true
	ps.selectedFile = nil // no file selected

	_, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'y'}})
	if cmd == nil {
		t.Fatal("y on complete with no file should return cmd")
	}
	msg := cmd()
	if _, ok := msg.(BackMsg); !ok {
		t.Errorf("expected BackMsg, got %T", msg)
	}
}

func TestProviderSetupCompleteNKey(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepComplete
	ps.fetchServers = true

	_, cmd := ps.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'n'}})
	if cmd == nil {
		t.Fatal("n on complete should return cmd")
	}
	msg := cmd()
	if _, ok := msg.(BackMsg); !ok {
		t.Errorf("expected BackMsg, got %T", msg)
	}
}

func TestProviderSetupSaveCredentials(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.confirmedProv = "protonvpn"
	ps.selectedFile = &configFile{
		privateKey: []byte("testkey123"),
		address:    "10.0.0.2/32",
	}

	cmd := ps.saveCredentials()
	if cmd == nil {
		t.Fatal("saveCredentials should return cmd")
	}
	msg := cmd()
	// Should succeed since we have a valid temp dir
	if _, ok := msg.(providerSetupSuccessMsg); !ok {
		t.Errorf("expected providerSetupSuccessMsg, got %T (%v)", msg, msg)
	}

	// Verify the provider file was created
	provFile := filepath.Join(ps.cfg.ConfigDir, "providers", "protonvpn.json")
	if _, err := os.Stat(provFile); os.IsNotExist(err) {
		t.Error("provider file should have been created")
	}
}

func TestProviderSetupOverwriteConfirmUnrecognized(t *testing.T) {
	ps := newTestProviderSetup(t)
	ps.step = StepConfirmOverwrite

	model, _ := ps.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'x'}})
	ps = model.(*ProviderSetup)
	if ps.step != StepConfirmOverwrite {
		t.Errorf("step = %d, should stay on StepConfirmOverwrite", ps.step)
	}
}

// TestDoFetchServersSuccess exercises doFetchServers with mocked dependencies.
func TestDoFetchServersSuccess(t *testing.T) {
	orig1 := fetchServers
	fetchServers = func(cacheDir string, force bool) error { return nil }
	t.Cleanup(func() { fetchServers = orig1 })

	orig2 := filterProviderServers
	filterProviderServers = func(cacheDir, prov string) ([]provider.Server, error) {
		return []provider.Server{{ServerName: "US-NY#1"}}, nil
	}
	t.Cleanup(func() { filterProviderServers = orig2 })

	ps := newTestProviderSetup(t)
	ps.confirmedProv = "protonvpn"
	cmd := ps.doFetchServers()
	if cmd == nil {
		t.Fatal("doFetchServers should return a cmd")
	}

	msg := cmd()
	if _, ok := msg.(providerFetchDoneMsg); !ok {
		t.Fatalf("expected providerFetchDoneMsg, got %T", msg)
	}
}

// TestDoFetchServersFetchError exercises doFetchServers when fetchServers fails.
func TestDoFetchServersFetchError(t *testing.T) {
	orig := fetchServers
	fetchServers = func(cacheDir string, force bool) error { return errForTest("network error") }
	t.Cleanup(func() { fetchServers = orig })

	ps := newTestProviderSetup(t)
	ps.confirmedProv = "protonvpn"
	cmd := ps.doFetchServers()
	msg := cmd()

	errMsg, ok := msg.(providerSetupErrorMsg)
	if !ok {
		t.Fatalf("expected providerSetupErrorMsg, got %T", msg)
	}
	if errMsg.err.Error() != "network error" {
		t.Errorf("error = %q, want 'network error'", errMsg.err.Error())
	}
}

// TestDoFetchServersFilterError exercises doFetchServers when filter fails.
func TestDoFetchServersFilterError(t *testing.T) {
	orig1 := fetchServers
	fetchServers = func(cacheDir string, force bool) error { return nil }
	t.Cleanup(func() { fetchServers = orig1 })

	orig2 := filterProviderServers
	filterProviderServers = func(cacheDir, prov string) ([]provider.Server, error) {
		return nil, errForTest("filter failed")
	}
	t.Cleanup(func() { filterProviderServers = orig2 })

	ps := newTestProviderSetup(t)
	ps.confirmedProv = "protonvpn"
	cmd := ps.doFetchServers()
	msg := cmd()

	errMsg, ok := msg.(providerSetupErrorMsg)
	if !ok {
		t.Fatalf("expected providerSetupErrorMsg, got %T", msg)
	}
	if errMsg.err.Error() != "filter failed" {
		t.Errorf("error = %q, want 'filter failed'", errMsg.err.Error())
	}
}
